### ISSUE TITLE
Interface updates

### ISSUE THREAD

**Issue by Dougoc** [globocom/graylog-plugin-oauth2#11]
### Update plugin interface

- Change title to "OAuth2 Settings"
> Description: This page is the only resource you need to set up the Graylog OAuth2 integration. 
- Change subtitle to "1. Basic Configuration"
- Remove field "Name" - Not used for setup. 
- Change order and descriptions to those informed below. 
1. Token Server URL
>  Description: "Full application URL to get token authorization"
2. User Data Server URL
>  Description: "Full application URL to get user data"
3. Client ID  
> Remove description
4. Client Secret 
> Remove description 

- Move up the check box to "Automatically create users", to "1. Basic Configuration" section, and change to the follow description:
> If checked, new users are automatically create in graylog if OAuth2 authentication ocurred successfuly. If unchecked, an administrator need to create user in graylog first.

- Default User Rule - Box selection (may be come filled with "Read" default rule)
> Description: Select default rule to associate all logged users.

**Comment by matheusdaluz** [comment]
we'll change, thanks !

**Comment by matheusdaluz** [comment]
#16
