### ISSUE TITLE
Can you provide instructions on how to use this with Google OAuth2?

### ISSUE THREAD

**Issue by trajano** [globocom/graylog-plugin-oauth2#20]
I set up the order as follows

![image](https://user-images.githubusercontent.com/110627/50917864-a7452380-140c-11e9-9e04-b179c54f0a0e.png)

And the configuration as follows 

![image](https://user-images.githubusercontent.com/110627/50917920-d3f93b00-140c-11e9-9774-aa8932fbc770.png)

**Comment by trajano** [comment]
Thanks, but I still don't see the "login with google" link when I access the page.

**Comment by matheusdaluz** [comment]
Your oauth screen should redirect to graylog.

**Comment by trajano** [comment]
The OAuth screen does not appear when is it supposed to appear?

**Comment by matheusdaluz** [comment]
the plugin is still in development and unfortunately does not have this functionality

**Comment by matheusdaluz** [comment]
we use nginx to do that

**Comment by matheusdaluz** [comment]
i'm fixing the plugin to work with google oauth2.0

**Comment by trajano** [comment]
Are you releasing it soon?

**Comment by matheusdaluz** [comment]
https://github.com/globocom/graylog-plugin-oauth2/wiki/How-use-Google-OAuth-with-plugin.

**Comment by matheusdaluz** [comment]
Steps to work with google.
