### ISSUE TITLE
Unable to update Oauth2 authenticator config

### ISSUE THREAD

**Issue by Mikulas** [globocom/graylog-plugin-oauth2#21]
I've installed the latest release `2.3/0.0.3` into latest graylog `2.5.1-2`.

When updating the configuration from the web admin, I get this error
> Unable to update Oauth2 authenticator config
> Updating Oauth2 config failed: CSRF protection header is missing. Please add a "X-Requested-By" header to your request.

It can be bypassed by copying the request the administration creates as cURL and manually adding the header as `-H 'X-Requested-By: XMLHttpRequest'`

The X-Requested-By header is required for all 2.5.0+ graylogs
> Since Graylog 2.5.0, all non-GET API requests must include and set a value for the X-Requested-By HTTP header. This is needed to prevent CSRF attacks.
> http://docs.graylog.org/en/2.5/pages/configuration/rest_api.html

**Comment by matheusdaluz** [comment]
you need install the version 2.5/0.0.3.
