### ISSUE TITLE
ERROR [OAuth2] java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by snackwagon** [globocom/graylog-plugin-oauth2#22]
Hello, I am trying to configure this plugin for use with OneLogin. It doesn't appear to be working and the only log entry generated is:

ERROR [OAuth2] java.lang.ArrayIndexOutOfBoundsException: 1

Any insight into what causes this?

Graylog version:  2.5.1+34194da, codename Trippy Trampoline
Plugin version: graylog-plugin-oauth2-2.5-0.0.3-SNAPSHOT.jar

**Comment by matheusdaluz** [comment]
These errors will be corrected, the last error is because of the jar compilation.

**Comment by schndr** [comment]
Hey @matheusdaluz, is there already a fix in place? What is the current status? I don't know the scope, but I'm happy to help.

**Comment by matheusdaluz** [comment]
We have not started yet, your help would be  welcome.

**Comment by schndr** [comment]
Ok, how does it work for you? How do you use the plugin? With a Nginx in front of it or directly the service? Which oauth provider?

**Comment by matheusdaluz** [comment]
we
