### ISSUE TITLE
graylog3 support

### ISSUE THREAD

**Issue by Ni-k0** [globocom/graylog-plugin-oauth2#27]
Hi, 
Are you planning to add support for Graylog3 ? 
I am getting the following error when trying to use graylog-plugin-oauth2-1.0.1-2.4-SNAPSHOT.jar with Graylog 3.0.1:
Plugin component missing for authenticator oauth2, this is an error.

**Comment by matheusdaluz** [comment]
Here is it https://github.com/globocom/graylog-plugin-oauth2/releases/tag/3.0%2F1.0.1

**Comment by cmeresse** [comment]
Hello,
Same error message for me with the version for graylog 3.x...
I'm not sure to understand the error message, is it a plugin packaging issue ?
